**********************************************************************
File "__main__", line 109, in __main__.logit_like_sum
Failed example:
    logit_like_sum(y, x, 2, 0.5)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\megan\anaconda3\lib\doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.logit_like_sum[0]>", line 1, in <module>
        logit_like_sum(y, x, 2, 0.5)
      File "<ipython-input-82-dfbdad159bd9>", line 121, in logit_like_sum
        if index == 0:
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
**********************************************************************
File "__main__", line 111, in __main__.logit_like_sum
Failed example:
    logit_like_sum(y, x, 2, 9)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\megan\anaconda3\lib\doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.logit_like_sum[1]>", line 1, in <module>
        logit_like_sum(y, x, 2, 9)
      File "<ipython-input-82-dfbdad159bd9>", line 121, in logit_like_sum
        if index == 0:
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
**********************************************************************
File "__main__", line 113, in __main__.logit_like_sum
Failed example:
    logit_like_sum(y, x, 8, 9)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\megan\anaconda3\lib\doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.logit_like_sum[2]>", line 1, in <module>
        logit_like_sum(y, x, 8, 9)
      File "<ipython-input-82-dfbdad159bd9>", line 121, in logit_like_sum
        if index == 0:
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
**********************************************************************
1 items had failures:
   3 of   3 in __main__.logit_like_sum
***Test Failed*** 3 failures.
Out[82]: TestResults(failed=3, attempted=12)
